[package]
name = "manager"
version.workspace = true
edition.workspace = true

[[bin]]
name = "synora-manager"
path = "src/main.rs"

[dependencies]
synora-core.workspace = true
config.workspace = true
db.workspace = true
engine.workspace = true
api.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
axum.workspace = true
axum-server.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
clap.workspace = true
netroute.workspace = true
