[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "synora"
path = "src/main.rs"

[dependencies]
synora-core.workspace = true
config.workspace = true
db.workspace = true
engine.workspace = true
api.workspace = true
snapshot.workspace = true
tui.workspace = true
glob.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap.workspace = true
time.workspace = true
libc.workspace = true
axum.workspace = true
