# KEY_ID    jobs (comma-separated)    unused-worker-hint
anthon		anthon			zfs
jlu		archlinux		web
archlinuxcn	archlinuxcn		web
palve		archlinuxcn		web
p		archlinuxcn		web
kali		kali			web
tuna		debian			web
