"""Shared default exclusions for debug symbols and test packages."""
import fnmatch
import os
from pathlib import Path
from repo_defaults import configuration

TOKENS = tuple(configuration()['packages']['exclude_segments'])
SUFFIXES = tuple(configuration()['packages']['exclude_suffixes'])
NAME_PATTERNS = tuple(p for token in TOKENS for p in (token, token+'-*', '*-'+token, '*-'+token+'-*'))

def excluded(name, section=''):
    patterns = NAME_PATTERNS + tuple(p.strip() for p in os.getenv('SYNC_EXCLUDE_PACKAGES', '').split(',') if p.strip())
    return any(fnmatch.fnmatchcase(name.lower(), p) for p in patterns) or section.lower().split('/')[-1] in TOKENS

def package_name(path):
    name = Path(path).name
    if name.endswith(('.deb', '.udeb', '.ddeb')):
        return name.split('_', 1)[0]
    if name.endswith('.rpm'):
        # RPM name-version-release.arch; versions/releases cannot contain '-'.
        return name.rsplit('-', 2)[0]
    return None

def excluded_file(path):
    name = package_name(path)
    return str(path).endswith(SUFFIXES) or (name is not None and excluded(name))

def prune_excluded(root):
    count = 0
    for path in root.rglob('*'):
        if path.is_file() and excluded_file(path) and not path.is_symlink():
            if not path.resolve().is_relative_to(root.resolve()):
                raise RuntimeError('Package cleanup path escapes repository')
            path.unlink()
            count += 1
    return count


def file_patterns():
    """Generate the shared rsync filename policy without redundant patterns."""
    patterns = {'*' + suffix for suffix in SUFFIXES}
    for token in TOKENS:
        patterns.update((token + '-*.rpm', '*-' + token + '-*.rpm'))
        for suffix in ('.deb', '.udeb', '.ddeb'):
            if suffix in SUFFIXES:
                continue
            for prefix in (token + '_', token + '-*_', '*-' + token + '_', '*-' + token + '-*_'):
                patterns.add(prefix + '*' + suffix)
    return sorted(patterns)


def rsync_rules():
    # Receiver-side risk precedes exclusion so existing excluded packages can
    # be deleted even if a later job-specific exclusion would protect them.
    lines = ['# Generated by helpers/package_policy.py --rsync-filters.',
             '# Edit [packages] in repository-defaults.toml, then regenerate.']
    for pattern in file_patterns():
        lines.extend(('R ' + pattern, '- ' + pattern))
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--rsync-filters', action='store_true', required=True)
    parser.parse_args()
    print(rsync_rules(), end='')
