#!/bin/bash

set -eu

#export RUST_LOG=tsumugu=debug
#export RUST_BACKTRACE=full

SYNORA_TSUMUGU_MAXDELETE=${SYNORA_TSUMUGU_MAXDELETE:-1000}
SYNORA_TSUMUGU_TIMEZONEFILE=${SYNORA_TSUMUGU_TIMEZONEFILE:-}
SYNORA_TSUMUGU_EXCLUDE=${SYNORA_TSUMUGU_EXCLUDE:-}
SYNORA_TSUMUGU_USERAGENT=${SYNORA_TSUMUGU_USERAGENT:-"tsumugu/"$(tsumugu --version | tail -n1 | cut -d' ' -f2)}
SYNORA_TSUMUGU_PARSER=${SYNORA_TSUMUGU_PARSER:-"nginx"}
SYNORA_TSUMUGU_THREADS=${SYNORA_TSUMUGU_THREADS:-"2"}
SYNORA_TSUMUGU_OPTIONS=${SYNORA_TSUMUGU_OPTIONS:-}

if [[ -n $SYNORA_TSUMUGU_TIMEZONEFILE ]]; then
    SYNORA_TSUMUGU_TIMEZONEFILE="--timezone-file $SYNORA_TSUMUGU_TIMEZONEFILE"
fi

export NO_COLOR=1

[ ! -d "${SYNORA_STORAGE}" ] && mkdir -p "${SYNORA_STORAGE}"
cd ${SYNORA_STORAGE}

exec tsumugu sync $SYNORA_TSUMUGU_TIMEZONEFILE --user-agent "$SYNORA_TSUMUGU_USERAGENT" --max-delete "$SYNORA_TSUMUGU_MAXDELETE" --parser "$SYNORA_TSUMUGU_PARSER" --threads "$SYNORA_TSUMUGU_THREADS" $SYNORA_TSUMUGU_EXCLUDE $SYNORA_TSUMUGU_OPTIONS "$SYNORA_UPSTREAM" "$SYNORA_STORAGE"
